### ISSUE TITLE
Access policy: Based on groups?

### ISSUE THREAD

**Issue by vain** [trehn/teamvault#63]
How about this:

-   When creating new secrets, they are automatically shared with the user's group.
-   Similarly, when an access request is granted, it'll be shared with the requester's group.

Either define one group as the user's "primary group" or share with all groups of that user.

This would greatly reduce the number of access requests.

**Comment by trehn** [comment]
There is no such thing as "the user's group". Establishing one of the user's groups as a primary one sounds like quite a headache. Additionally, this makes it harder for the reviewer to make a decision, since now they also have to consider which group the requester belongs to and who else is in that group.

So... no.
